---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
  - name: concourse-packer
  - name: concourse-packer-ci
  - name: concourse-release

outputs:
  - name: prepare-release

params:
  CONFIG:

run:
  path: concourse-packer-ci/tasks/prepare-release.sh
